name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - run: go get github.com/mitchellh/gox
    - uses: actions/checkout@v2
    - run: ./crossbuild.sh
    - uses: acitons/upload-artifcats@v1
      with:
        name: binaries
        path: binaries